
description = "Pensando Documentation Site"
## Setting this to true will add a "noindex" to *EVERY* page on the site..
removefromexternalsearch = false

# First one is picked as the Twitter card image if not set on page.
images = ["images/pensando_logo.svg"]

flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"

#sidebar_direction = "sidebar_left"

