FROM python:3.7-alpine
WORKDIR /
COPY . .
COPY .gdocs /root
# RUN apk --update add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev
RUN apk add unzip nano bash chromium chromium-chromedriver
RUN pip install --no-cache-dir -r requirements.txt 

ENTRYPOINT [ "python", "./readgdoc.py" ]
