[[docs]]
  name = "Policy Services Manager"
  weight = 1
  identifier = "psm"
  url = "/psm/"

[[docs]]
  name = "Distributed Services Card"
  weight = 5
  identifier = "dsc"
  url = "/dsc/"

[[docs]]
  name = "Host Drivers"
  weight = 15
  identifier = "drivers"
  post = "break"
  url = "/drivers/"


######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "Pensando Website"
    weight = 1
    identifier = "pensando_website"
    post = "external"
    url = "https://pensando.io/"

  [[global]]
    name = "Support"
    weight = 5
    identifier = "support"
    post = "external"
    url = "https://support.pensando.io/"
